import type { MvpCardView } from "@/types/cards";

const baseCard: Omit<MvpCardView, "templateId" | "tokenId" | "displayName" | "symbol" | "rarity" | "edition" | "imageUrl"> = {
  slug: "guest-preview-token",
  primaryChain: "Ethereum",
  faction: "PANTHEON",
  plannedSupply: 730,
  issuedSupply: 127,
  remainingSupply: 603,
  owned: false,
  instanceCount: 0,
  cardText: "Preview card for the MCG pack reveal demo.",
  flavorText: "A short reveal lets visitors feel the pull before they connect.",
  cardNumber: "S01-001",
  setCode: "GENESIS",
  setEditionLabel: "Edition 1",
  setOrder: 1,
  editionNumber: 1,
};

export const GUEST_PACK_PREVIEW_CARDS: MvpCardView[] = [
  {
    ...baseCard,
    templateId: "guest_preview_common_base",
    tokenId: "guest_tok_dogecoin",
    displayName: "Dogecoin",
    symbol: "DOGE",
    rarity: "COMMON",
    edition: "BASE",
    imageUrl: "https://coin-images.coingecko.com/coins/images/5/large/dogecoin.png?1696501409",
  },
  {
    ...baseCard,
    templateId: "guest_preview_uncommon_reverse",
    tokenId: "guest_tok_shiba-inu",
    displayName: "Shiba Inu",
    symbol: "SHIB",
    rarity: "UNCOMMON",
    edition: "REVERSE",
    imageUrl: "https://coin-images.coingecko.com/coins/images/11939/large/shiba.png?1696511800",
    setOrder: 2,
    editionNumber: 2,
  },
  {
    ...baseCard,
    templateId: "guest_preview_rare_brillante",
    tokenId: "guest_tok_pepe",
    displayName: "Pepe",
    symbol: "PEPE",
    rarity: "RARE",
    edition: "BRILLANTE",
    imageUrl: "https://coin-images.coingecko.com/coins/images/29850/large/pepe-token.jpeg?1696528776",
    setOrder: 3,
    editionNumber: 3,
  },
  {
    ...baseCard,
    templateId: "guest_preview_epic_holo",
    tokenId: "guest_tok_bonk",
    displayName: "Bonk",
    symbol: "BONK",
    rarity: "EPIC",
    edition: "HOLO",
    imageUrl: "https://coin-images.coingecko.com/coins/images/28600/large/bonk.jpg?1696527587",
    setOrder: 4,
    editionNumber: 4,
  },
  {
    ...baseCard,
    templateId: "guest_preview_legendary_full_art",
    tokenId: "guest_tok_wif",
    displayName: "dogwifhat",
    symbol: "WIF",
    rarity: "LEGENDARY",
    edition: "FULL_ART",
    imageUrl: "https://coin-images.coingecko.com/coins/images/33566/large/dogwifhat.jpg?1702499428",
    plannedSupply: 45,
    issuedSupply: 8,
    remainingSupply: 37,
    cardNumber: "S01-025",
    setOrder: 25,
    editionNumber: 5,
  },
];
