import type { MilestoneType } from "@/lib/domain/quests/social";

export type MilestoneSeedDefinition = {
  code: string;
  slug: string;
  seedKey: string;
  title: string;
  adminTitle: string;
  category: string;
  userDescription: string;
  adminDescription: string;
  metricKey: MilestoneType;
  threshold: number;
  rewardPoints: number;
  sortOrder: number;
  active: boolean;
  unique: true;
  repeatable: false;
};

export const MILESTONE_SEED_DEFINITIONS: MilestoneSeedDefinition[] = [
  {
    code: "ms_open_packs_01",
    slug: "open-packs-1",
    seedKey: "MILESTONE_V1_OPEN_PACKS_1",
    title: "First pack opened",
    adminTitle: "Milestone · Open packs · 1",
    category: "OPEN_PACKS",
    userDescription: "Open your first pack.",
    adminDescription: "First core-loop action to validate onboarding engagement.",
    metricKey: "PACK_OPEN_COUNT",
    threshold: 1,
    rewardPoints: 100,
    sortOrder: 10,
    active: true,
    unique: true,
    repeatable: false,
  },
  {
    code: "ms_open_packs_05",
    slug: "open-packs-5",
    seedKey: "MILESTONE_V1_OPEN_PACKS_5",
    title: "Pack opener",
    adminTitle: "Milestone · Open packs · 5",
    category: "OPEN_PACKS",
    userDescription: "Open 5 packs.",
    adminDescription: "Early repeat engagement on opening loop.",
    metricKey: "PACK_OPEN_COUNT",
    threshold: 5,
    rewardPoints: 250,
    sortOrder: 20,
    active: true,
    unique: true,
    repeatable: false,
  },
  {
    code: "ms_open_packs_20",
    slug: "open-packs-20",
    seedKey: "MILESTONE_V1_OPEN_PACKS_20",
    title: "Pack veteran",
    adminTitle: "Milestone · Open packs · 20",
    category: "OPEN_PACKS",
    userDescription: "Open 20 packs.",
    adminDescription: "Sustained interaction with pack loop.",
    metricKey: "PACK_OPEN_COUNT",
    threshold: 20,
    rewardPoints: 800,
    sortOrder: 30,
    active: true,
    unique: true,
    repeatable: false,
  },
  {
    code: "ms_total_cards_25",
    slug: "total-cards-25",
    seedKey: "MILESTONE_V1_TOTAL_CARDS_25",
    title: "Collector I",
    adminTitle: "Milestone · Total cards · 25",
    category: "TOTAL_CARDS_COLLECTED",
    userDescription: "Collect 25 cards.",
    adminDescription: "Tracks absolute collection volume.",
    metricKey: "TOTAL_CARDS_COLLECTED",
    threshold: 25,
    rewardPoints: 200,
    sortOrder: 40,
    active: true,
    unique: true,
    repeatable: false,
  },
  {
    code: "ms_total_cards_100",
    slug: "total-cards-100",
    seedKey: "MILESTONE_V1_TOTAL_CARDS_100",
    title: "Collector II",
    adminTitle: "Milestone · Total cards · 100",
    category: "TOTAL_CARDS_COLLECTED",
    userDescription: "Collect 100 cards.",
    adminDescription: "Mid-term collection growth checkpoint.",
    metricKey: "TOTAL_CARDS_COLLECTED",
    threshold: 100,
    rewardPoints: 750,
    sortOrder: 50,
    active: true,
    unique: true,
    repeatable: false,
  },
  {
    code: "ms_unique_cards_10",
    slug: "unique-cards-10",
    seedKey: "MILESTONE_V1_UNIQUE_CARDS_10",
    title: "Diversity I",
    adminTitle: "Milestone · Unique cards · 10",
    category: "UNIQUE_CARDS_COLLECTED",
    userDescription: "Own 10 unique card templates.",
    adminDescription: "Measures breadth, not volume.",
    metricKey: "UNIQUE_CARDS_COLLECTED",
    threshold: 10,
    rewardPoints: 220,
    sortOrder: 60,
    active: true,
    unique: true,
    repeatable: false,
  },
  {
    code: "ms_unique_cards_25",
    slug: "unique-cards-25",
    seedKey: "MILESTONE_V1_UNIQUE_CARDS_25",
    title: "Diversity II",
    adminTitle: "Milestone · Unique cards · 25",
    category: "UNIQUE_CARDS_COLLECTED",
    userDescription: "Own 25 unique card templates.",
    adminDescription: "Collection completion oriented checkpoint.",
    metricKey: "UNIQUE_CARDS_COLLECTED",
    threshold: 25,
    rewardPoints: 700,
    sortOrder: 70,
    active: true,
    unique: true,
    repeatable: false,
  },
  {
    code: "ms_contests_joined_1",
    slug: "contests-joined-1",
    seedKey: "MILESTONE_V1_CONTESTS_JOINED_1",
    title: "First contest entry",
    adminTitle: "Milestone · Contests joined · 1",
    category: "CONTESTS_JOINED",
    userDescription: "Join your first contest.",
    adminDescription: "Activation of contest loop.",
    metricKey: "CONTESTS_JOINED",
    threshold: 1,
    rewardPoints: 150,
    sortOrder: 80,
    active: true,
    unique: true,
    repeatable: false,
  },
  {
    code: "ms_contests_joined_10",
    slug: "contests-joined-10",
    seedKey: "MILESTONE_V1_CONTESTS_JOINED_10",
    title: "Contest regular",
    adminTitle: "Milestone · Contests joined · 10",
    category: "CONTESTS_JOINED",
    userDescription: "Join 10 contests.",
    adminDescription: "Retention marker on competitive loop.",
    metricKey: "CONTESTS_JOINED",
    threshold: 10,
    rewardPoints: 900,
    sortOrder: 90,
    active: true,
    unique: true,
    repeatable: false,
  },
  {
    code: "ms_contests_won_1",
    slug: "contests-won-1",
    seedKey: "MILESTONE_V1_CONTESTS_WON_1",
    title: "First victory",
    adminTitle: "Milestone · Contests won · 1",
    category: "CONTESTS_WON",
    userDescription: "Win 1 contest.",
    adminDescription: "Performance-based milestone (rank = 1).",
    metricKey: "CONTESTS_WON",
    threshold: 1,
    rewardPoints: 1200,
    sortOrder: 100,
    active: true,
    unique: true,
    repeatable: false,
  },
  {
    code: "ms_rare_plus_10",
    slug: "rare-plus-cards-10",
    seedKey: "MILESTONE_V1_RARE_PLUS_10",
    title: "Rare hunter",
    adminTitle: "Milestone · Rare+ owned · 10",
    category: "RARE_PLUS_CARDS_OWNED",
    userDescription: "Own 10 Rare+ cards.",
    adminDescription: "Tracks rarity quality of inventory.",
    metricKey: "RARE_PLUS_CARDS_OWNED",
    threshold: 10,
    rewardPoints: 500,
    sortOrder: 110,
    active: true,
    unique: true,
    repeatable: false,
  },
  {
    code: "ms_epic_plus_5",
    slug: "epic-plus-cards-5",
    seedKey: "MILESTONE_V1_EPIC_PLUS_5",
    title: "Epic collector",
    adminTitle: "Milestone · Epic+ owned · 5",
    category: "EPIC_PLUS_CARDS_OWNED",
    userDescription: "Own 5 Epic+ cards.",
    adminDescription: "High-rarity ownership checkpoint.",
    metricKey: "EPIC_PLUS_CARDS_OWNED",
    threshold: 5,
    rewardPoints: 900,
    sortOrder: 120,
    active: true,
    unique: true,
    repeatable: false,
  },
  {
    code: "ms_legendary_1",
    slug: "legendary-cards-1",
    seedKey: "MILESTONE_V1_LEGENDARY_1",
    title: "Legend awakened",
    adminTitle: "Milestone · Legendary owned · 1",
    category: "LEGENDARY_CARDS_OWNED",
    userDescription: "Own 1 Legendary card.",
    adminDescription: "First top-tier rarity acquisition.",
    metricKey: "LEGENDARY_CARDS_OWNED",
    threshold: 1,
    rewardPoints: 1500,
    sortOrder: 130,
    active: true,
    unique: true,
    repeatable: false,
  },
  {
    code: "ms_rewards_claimed_5",
    slug: "rewards-claimed-5",
    seedKey: "MILESTONE_V1_REWARDS_CLAIMED_5",
    title: "Quest closer",
    adminTitle: "Milestone · Rewards claimed · 5",
    category: "REWARDS_CLAIMED",
    userDescription: "Claim 5 quest rewards.",
    adminDescription: "Engagement with quest reward loop.",
    metricKey: "REWARDS_CLAIMED",
    threshold: 5,
    rewardPoints: 600,
    sortOrder: 140,
    active: true,
    unique: true,
    repeatable: false,
  },
  {
    code: "ms_reward_points_5000",
    slug: "reward-points-earned-5000",
    seedKey: "MILESTONE_V1_REWARD_POINTS_5000",
    title: "Points powerhouse",
    adminTitle: "Milestone · Reward points earned · 5000",
    category: "REWARD_POINTS_EARNED",
    userDescription: "Earn 5,000 points from rewards.",
    adminDescription: "Long-term reward accumulation marker.",
    metricKey: "REWARD_POINTS_EARNED",
    threshold: 5000,
    rewardPoints: 1200,
    sortOrder: 150,
    active: true,
    unique: true,
    repeatable: false,
  },
];

if (MILESTONE_SEED_DEFINITIONS.length !== 15) {
  throw new Error(`Expected 15 milestones, found ${MILESTONE_SEED_DEFINITIONS.length}`);
}
