import type { MilestoneType } from "@/lib/domain/quests/social";

export type MilestoneSeedDefinition = {
  code: string;
  slug: string;
  seedKey: string;
  title: string;
  adminTitle: string;
  category: string;
  userDescription: string;
  adminDescription: string;
  metricKey: MilestoneType;
  threshold: number;
  rewardPoints: number;
  sortOrder: number;
  active: boolean;
  unique: true;
  repeatable: false;
};

export const MILESTONE_SEED_DEFINITIONS: MilestoneSeedDefinition[] = [
  // ── Packs opened ─────────────────────────────────────────────────────────
  // Old codes preserved for DB backward-compat; new entries use new codes
  {
    code: "ms_open_packs_01",
    slug: "packs-opened-1",
    seedKey: "MILESTONE_V2_PACK_OPEN_1",
    title: "First unboxing",
    adminTitle: "Milestone · Packs opened · 1",
    category: "OPEN_PACKS",
    userDescription: "Open 1 pack.",
    adminDescription: "First core-loop action to validate onboarding engagement.",
    metricKey: "PACK_OPEN_COUNT",
    threshold: 1,
    rewardPoints: 100,
    sortOrder: 10,
    active: true,
    unique: true,
    repeatable: false,
  },
  {
    code: "ms_open_packs_05",
    slug: "packs-opened-5",
    seedKey: "MILESTONE_V2_PACK_OPEN_5",
    title: "Pack opener",
    adminTitle: "Milestone · Packs opened · 5",
    category: "OPEN_PACKS",
    userDescription: "Open 5 packs.",
    adminDescription: "Early repeat engagement on opening loop.",
    metricKey: "PACK_OPEN_COUNT",
    threshold: 5,
    rewardPoints: 500,
    sortOrder: 20,
    active: true,
    unique: true,
    repeatable: false,
  },
  {
    code: "ms_open_packs_20",
    slug: "packs-opened-20",
    seedKey: "MILESTONE_V2_PACK_OPEN_20",
    title: "Pack veteran",
    adminTitle: "Milestone · Packs opened · 20",
    category: "OPEN_PACKS",
    userDescription: "Open 20 packs.",
    adminDescription: "Sustained interaction with pack loop.",
    metricKey: "PACK_OPEN_COUNT",
    threshold: 20,
    rewardPoints: 2000,
    sortOrder: 30,
    active: true,
    unique: true,
    repeatable: false,
  },
  {
    code: "ms_pack_50",
    slug: "packs-opened-50",
    seedKey: "MILESTONE_V2_PACK_OPEN_50",
    title: "Pack master",
    adminTitle: "Milestone · Packs opened · 50",
    category: "OPEN_PACKS",
    userDescription: "Open 50 packs.",
    adminDescription: "High-volume pack opening commitment.",
    metricKey: "PACK_OPEN_COUNT",
    threshold: 50,
    rewardPoints: 5000,
    sortOrder: 40,
    active: true,
    unique: true,
    repeatable: false,
  },
  {
    code: "ms_pack_200",
    slug: "packs-opened-200",
    seedKey: "MILESTONE_V2_PACK_OPEN_200",
    title: "Pack legend",
    adminTitle: "Milestone · Packs opened · 200",
    category: "OPEN_PACKS",
    userDescription: "Open 200 packs.",
    adminDescription: "Top-tier pack opening milestone.",
    metricKey: "PACK_OPEN_COUNT",
    threshold: 200,
    rewardPoints: 15000,
    sortOrder: 50,
    active: true,
    unique: true,
    repeatable: false,
  },

  // ── Cards collected — total ───────────────────────────────────────────────
  {
    code: "ms_total_cards_25",
    slug: "cards-collected-25",
    seedKey: "MILESTONE_V2_TOTAL_CARDS_25",
    title: "Newcomer",
    adminTitle: "Milestone · Cards collected · 25",
    category: "TOTAL_CARDS_COLLECTED",
    userDescription: "Collect 25 cards.",
    adminDescription: "Tracks absolute collection volume — entry checkpoint.",
    metricKey: "TOTAL_CARDS_COLLECTED",
    threshold: 25,
    rewardPoints: 250,
    sortOrder: 110,
    active: true,
    unique: true,
    repeatable: false,
  },
  {
    code: "ms_total_cards_100",
    slug: "cards-collected-100",
    seedKey: "MILESTONE_V2_TOTAL_CARDS_100",
    title: "Accumulator",
    adminTitle: "Milestone · Cards collected · 100",
    category: "TOTAL_CARDS_COLLECTED",
    userDescription: "Collect 100 cards.",
    adminDescription: "Mid-term collection growth checkpoint.",
    metricKey: "TOTAL_CARDS_COLLECTED",
    threshold: 100,
    rewardPoints: 750,
    sortOrder: 120,
    active: true,
    unique: true,
    repeatable: false,
  },
  {
    code: "ms_cards_500",
    slug: "cards-collected-500",
    seedKey: "MILESTONE_V2_TOTAL_CARDS_500",
    title: "Hoarder",
    adminTitle: "Milestone · Cards collected · 500",
    category: "TOTAL_CARDS_COLLECTED",
    userDescription: "Collect 500 cards.",
    adminDescription: "Serious collection volume.",
    metricKey: "TOTAL_CARDS_COLLECTED",
    threshold: 500,
    rewardPoints: 2500,
    sortOrder: 130,
    active: true,
    unique: true,
    repeatable: false,
  },
  {
    code: "ms_cards_1000",
    slug: "cards-collected-1000",
    seedKey: "MILESTONE_V2_TOTAL_CARDS_1000",
    title: "Vault",
    adminTitle: "Milestone · Cards collected · 1000",
    category: "TOTAL_CARDS_COLLECTED",
    userDescription: "Collect 1,000 cards.",
    adminDescription: "High-volume collection milestone.",
    metricKey: "TOTAL_CARDS_COLLECTED",
    threshold: 1000,
    rewardPoints: 5000,
    sortOrder: 140,
    active: true,
    unique: true,
    repeatable: false,
  },
  {
    code: "ms_cards_5000",
    slug: "cards-collected-5000",
    seedKey: "MILESTONE_V2_TOTAL_CARDS_5000",
    title: "Infinite",
    adminTitle: "Milestone · Cards collected · 5000",
    category: "TOTAL_CARDS_COLLECTED",
    userDescription: "Collect 5,000 cards.",
    adminDescription: "Top-tier collection volume milestone.",
    metricKey: "TOTAL_CARDS_COLLECTED",
    threshold: 5000,
    rewardPoints: 20000,
    sortOrder: 150,
    active: true,
    unique: true,
    repeatable: false,
  },

  // ── Unique cards ──────────────────────────────────────────────────────────
  {
    code: "ms_unique_cards_10",
    slug: "unique-cards-10",
    seedKey: "MILESTONE_V2_UNIQUE_CARDS_10",
    title: "Curious",
    adminTitle: "Milestone · Unique cards · 10",
    category: "UNIQUE_CARDS_COLLECTED",
    userDescription: "Own 10 unique cards.",
    adminDescription: "Measures breadth — early checkpoint.",
    metricKey: "UNIQUE_CARDS_COLLECTED",
    threshold: 10,
    rewardPoints: 200,
    sortOrder: 210,
    active: true,
    unique: true,
    repeatable: false,
  },
  {
    code: "ms_unique_cards_25",
    slug: "unique-cards-25",
    seedKey: "MILESTONE_V2_UNIQUE_CARDS_25",
    title: "Explorer",
    adminTitle: "Milestone · Unique cards · 25",
    category: "UNIQUE_CARDS_COLLECTED",
    userDescription: "Own 25 unique cards.",
    adminDescription: "Collection diversity mid-checkpoint.",
    metricKey: "UNIQUE_CARDS_COLLECTED",
    threshold: 25,
    rewardPoints: 500,
    sortOrder: 220,
    active: true,
    unique: true,
    repeatable: false,
  },
  {
    code: "ms_unique_50",
    slug: "unique-cards-50",
    seedKey: "MILESTONE_V2_UNIQUE_CARDS_50",
    title: "Connoisseur",
    adminTitle: "Milestone · Unique cards · 50",
    category: "UNIQUE_CARDS_COLLECTED",
    userDescription: "Own 50 unique cards.",
    adminDescription: "Significant collection breadth.",
    metricKey: "UNIQUE_CARDS_COLLECTED",
    threshold: 50,
    rewardPoints: 1500,
    sortOrder: 230,
    active: true,
    unique: true,
    repeatable: false,
  },
  {
    code: "ms_unique_100",
    slug: "unique-cards-100",
    seedKey: "MILESTONE_V2_UNIQUE_CARDS_100",
    title: "Archivist",
    adminTitle: "Milestone · Unique cards · 100",
    category: "UNIQUE_CARDS_COLLECTED",
    userDescription: "Own 100 unique cards.",
    adminDescription: "Deep collection diversity.",
    metricKey: "UNIQUE_CARDS_COLLECTED",
    threshold: 100,
    rewardPoints: 4000,
    sortOrder: 240,
    active: true,
    unique: true,
    repeatable: false,
  },
  {
    code: "ms_unique_200",
    slug: "unique-cards-200",
    seedKey: "MILESTONE_V2_UNIQUE_CARDS_200",
    title: "Omnivore",
    adminTitle: "Milestone · Unique cards · 200",
    category: "UNIQUE_CARDS_COLLECTED",
    userDescription: "Own 200 unique cards.",
    adminDescription: "Top-tier collection diversity milestone.",
    metricKey: "UNIQUE_CARDS_COLLECTED",
    threshold: 200,
    rewardPoints: 12000,
    sortOrder: 250,
    active: true,
    unique: true,
    repeatable: false,
  },

  // ── Contests entered ──────────────────────────────────────────────────────
  {
    code: "ms_contests_joined_1",
    slug: "contests-joined-1",
    seedKey: "MILESTONE_V2_CONTESTS_JOINED_1",
    title: "First entry",
    adminTitle: "Milestone · Contests joined · 1",
    category: "CONTESTS_JOINED",
    userDescription: "Join 1 contest.",
    adminDescription: "Activation of contest loop.",
    metricKey: "CONTESTS_JOINED",
    threshold: 1,
    rewardPoints: 150,
    sortOrder: 310,
    active: true,
    unique: true,
    repeatable: false,
  },
  {
    code: "ms_cj_5",
    slug: "contests-joined-5",
    seedKey: "MILESTONE_V2_CONTESTS_JOINED_5",
    title: "Regular",
    adminTitle: "Milestone · Contests joined · 5",
    category: "CONTESTS_JOINED",
    userDescription: "Join 5 contests.",
    adminDescription: "Early contest retention checkpoint.",
    metricKey: "CONTESTS_JOINED",
    threshold: 5,
    rewardPoints: 600,
    sortOrder: 320,
    active: true,
    unique: true,
    repeatable: false,
  },
  {
    code: "ms_contests_joined_10",
    slug: "contests-joined-10",
    seedKey: "MILESTONE_V2_CONTESTS_JOINED_10",
    title: "Competitor",
    adminTitle: "Milestone · Contests joined · 10",
    category: "CONTESTS_JOINED",
    userDescription: "Join 10 contests.",
    adminDescription: "Retention marker on competitive loop.",
    metricKey: "CONTESTS_JOINED",
    threshold: 10,
    rewardPoints: 1500,
    sortOrder: 330,
    active: true,
    unique: true,
    repeatable: false,
  },
  {
    code: "ms_cj_50",
    slug: "contests-joined-50",
    seedKey: "MILESTONE_V2_CONTESTS_JOINED_50",
    title: "Grinder",
    adminTitle: "Milestone · Contests joined · 50",
    category: "CONTESTS_JOINED",
    userDescription: "Join 50 contests.",
    adminDescription: "High-volume contest participation.",
    metricKey: "CONTESTS_JOINED",
    threshold: 50,
    rewardPoints: 5000,
    sortOrder: 340,
    active: true,
    unique: true,
    repeatable: false,
  },
  {
    code: "ms_cj_100",
    slug: "contests-joined-100",
    seedKey: "MILESTONE_V2_CONTESTS_JOINED_100",
    title: "Arena lord",
    adminTitle: "Milestone · Contests joined · 100",
    category: "CONTESTS_JOINED",
    userDescription: "Join 100 contests.",
    adminDescription: "Top-tier contest participation milestone.",
    metricKey: "CONTESTS_JOINED",
    threshold: 100,
    rewardPoints: 12000,
    sortOrder: 350,
    active: true,
    unique: true,
    repeatable: false,
  },

  // ── Contest wins ──────────────────────────────────────────────────────────
  {
    code: "ms_contests_won_1",
    slug: "contests-won-1",
    seedKey: "MILESTONE_V2_CONTESTS_WON_1",
    title: "First blood",
    adminTitle: "Milestone · Contests won · 1",
    category: "CONTESTS_WON",
    userDescription: "Win 1 contest.",
    adminDescription: "Performance-based milestone — first win.",
    metricKey: "CONTESTS_WON",
    threshold: 1,
    rewardPoints: 1200,
    sortOrder: 410,
    active: true,
    unique: true,
    repeatable: false,
  },
  {
    code: "ms_cw_5",
    slug: "contests-won-5",
    seedKey: "MILESTONE_V2_CONTESTS_WON_5",
    title: "On a streak",
    adminTitle: "Milestone · Contests won · 5",
    category: "CONTESTS_WON",
    userDescription: "Win 5 contests.",
    adminDescription: "Consistent performance checkpoint.",
    metricKey: "CONTESTS_WON",
    threshold: 5,
    rewardPoints: 4000,
    sortOrder: 420,
    active: true,
    unique: true,
    repeatable: false,
  },
  {
    code: "ms_cw_20",
    slug: "contests-won-20",
    seedKey: "MILESTONE_V2_CONTESTS_WON_20",
    title: "Dominant",
    adminTitle: "Milestone · Contests won · 20",
    category: "CONTESTS_WON",
    userDescription: "Win 20 contests.",
    adminDescription: "Elite performance milestone.",
    metricKey: "CONTESTS_WON",
    threshold: 20,
    rewardPoints: 12000,
    sortOrder: 430,
    active: true,
    unique: true,
    repeatable: false,
  },
  {
    code: "ms_cw_50",
    slug: "contests-won-50",
    seedKey: "MILESTONE_V2_CONTESTS_WON_50",
    title: "Untouchable",
    adminTitle: "Milestone · Contests won · 50",
    category: "CONTESTS_WON",
    userDescription: "Win 50 contests.",
    adminDescription: "Top-tier contest wins milestone.",
    metricKey: "CONTESTS_WON",
    threshold: 50,
    rewardPoints: 25000,
    sortOrder: 440,
    active: true,
    unique: true,
    repeatable: false,
  },

  // ── Invitations ───────────────────────────────────────────────────────────
  {
    code: "ms_inv_1",
    slug: "invites-1",
    seedKey: "MILESTONE_V2_INVITED_FRIENDS_1",
    title: "Recruiter",
    adminTitle: "Milestone · Invites · 1",
    category: "INVITED_FRIENDS",
    userDescription: "Invite 1 friend.",
    adminDescription: "Referral activation — first successful invite.",
    metricKey: "INVITED_FRIENDS",
    threshold: 1,
    rewardPoints: 1000,
    sortOrder: 510,
    active: true,
    unique: true,
    repeatable: false,
  },
];

if (MILESTONE_SEED_DEFINITIONS.length !== 15) {
  throw new Error(`Expected 15 milestones, found ${MILESTONE_SEED_DEFINITIONS.length}`);
}
